# AWS DB Server (??? ?? ??)
spring.datasource.url=jdbc:mariadb://10.0.1.178:3306/test1?permitMysqlScheme
spring.datasource.username=jinma
spring.datasource.password=0264


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false