spring.application.name=maple
spring.profiles.active=local

# Nexon Open API
nexon.api.base-url=https://open.api.nexon.com
nexon.api.key=test_7986a4a8f2856266a93235060e53c528f8dd3fcae4341fd8d88f24663345e6d3efe8d04e6d233bd35cf2fabdeb93fb0d

# Local DB
spring.datasource.url=jdbc:mariadb://localhost:3306/test1?permitMysqlScheme
spring.datasource.username=root
spring.datasource.password=0264
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA & Cache
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=180s

# JWT
jwt.secret=bWFwbGVTZWNyZXRLZXlGb3JKd3RUb2tlblNpZ25pbmdQbGVhc2VDaGFuZ2VUaGlz
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000